const request = require('request');

const fetchMyIP = function(callback) {
  request('https://api.ipify.org?format=json', (error, response, body) => {
    
    if (error !== null) {
      // return autogenerated error message
      return callback(error, null);
       
    } if (response.statusCode !== 200) {
      
      callback(Error(`Status Code ${response.statusCode} when fetching IP: ${body}`), null);
    
    } else if (callback) {
      const IP = JSON.parse(body).ip;
      callback(null, IP);
    }
  });
};


const fetchCoordsByIp = function(ip, callback) {
  request(`https://freegeoip.app/json/${ip}`, (error, response, body) => {
    
    if (error) {
      // return autogenerated error message
      callback(error, null);
      
       
    } else if (response.statusCode !== 200) {// ISSUE: callback is not a function
      
      
      callback(Error(`Status Code ${response.statusCode} when fetching Coordinates for IP: ${body}`), null);
      return;
    
    } else {
      const geoCoordinates = { latitude: JSON.parse(body).latitude, longitude: JSON.parse(body).longitude };
     
      callback(null, geoCoordinates);
    }
  });
};


module.exports = { fetchMyIP, fetchCoordsByIp };

// fetchMyIP, fetchCoordsByIp, fetchISSFlyOverTimes