const request = require('request');

const fetchMyIP = function(callback) {
  request('https://api.ipify.org?format=json', (error, response, body) => {
    
    if (error !== null) {
      // return autogenerated error message
      return callback(error, null);
       
    } if (response.statusCode !== 200) {
      callback(Error(`Status Code ${response.statusCode} when fetching IP: ${body}`), null);
    
    } else if (callback) {
      const IP = JSON.parse(body).ip;
      callback(null, IP);
    }
  });
};


module.exports = { fetchMyIP };